### ISSUE TITLE
The documentation has error

### ISSUE THREAD

**Issue by cenyu2018** [nsetzer/mpgameserver#1]
The ECHO sample programs in the documentation has error

**Comment by nsetzer** [comment]
could you please add the error message or stack trace that you are seeing?

From a clean checkout you should be able to run these two commands in separate terminal windows. You will need to install the requirements first.
```
python3 -m demo.echoserver
python3 -m demo.echoclient
```

**Comment by cenyu2018** [comment]
Sorry, my problem is not clearly described, I mean that the echo_server example in /docs/example.md is wrong, and the program in the demo folder is availible.Tks
