### ISSUE TITLE
Using ServerMessageDispatcher or ClientMessageDispatcher with future annotations

### ISSUE THREAD

**Issue by Aman-Anas** [nsetzer/mpgameserver#3]
In my project, I use the `from __future__ import annotations` syntax in my resources scripts, but when this flag is activated, the message dispatcher fails to register the message types. This is because the new annotation system converts the types to strings. The result is that I get DispatchErrors despite having registered the types.

I found a relatively simple solution, which is to add the new `eval_str` argument to the `inspect.signature()` calls in dispatch.py. I think it may only be present in 3.10 though, so maybe there would need to be an alternative for 3.9 support. This solution seems to work well for me though.

```py
sig = inspect.signature(method, eval_str=True) # New argument here
args = list(sig.parameters.items())
```

**Comment by nsetzer** [comment]
Hello @Aman-Anas, If you make a PR with this change Ill take a look at support for 3.9.

**Comment by Aman-Anas** [comment]
⬆️  Made the PR ❤️ 

Maybe for 3.9, it could just check the version and print a warning not to use future annotations?

**Comment by Aman-Anas** [comment]
Closing this issue since it's been already been fixed and merged. Thanks!
