### ISSUE TITLE
Update PyPI package

### ISSUE THREAD

**Issue by Aman-Anas** [nsetzer/mpgameserver#6]
This is not a major issue, but the package version on PyPI is from December 2021. It would be good to update it (e.g. future annotation support etc) 😀

**Comment by nsetzer** [comment]
As soon as I get a chance Ill release a new update on pypi with just the future annotation support.

I don't have a ton of time right now to work on this, but things may clear up in the future soon. 

I have finalized a design for Client Side Prediction that I am working on integrating, but I have no idea when Ill be ready to merge that in.
