### ISSUE TITLE
EchoServer Example isn't working

### ISSUE THREAD

**Issue by TKirchmeier** [nsetzer/mpgameserver#7]
Hi,

With this package you had a great idea . 

However, by running the EchoServer example I got some errors. 

1. pyOpenSSL version
The current pyOpenSSL version of 24.0 raises the following error: 
ModuleNotFoundError: No module named 'cryptography.hazmat.backends.openssl.ec'

After a short search I fount a comment on [stackoverflow](https://stackoverflow.com/questions/32518458/importerror-no-module-named-cryptography-hazmat-bindings-openssl). With the version 21.1.0 of pyOpenSSL it worked. 

2. PingHandler
There is no PingHandler in your project, I think you mean EventHandler instead.?

3. There is no ping
By using the EventHandler the server shows a reception by the client, but it seams that the client doesn't wait for the connection status. 

Next I will try to use your Getting Started Guide to create my one PingPong example.

**Comment by nsetzer** [comment]
Hi, Thanks for the feedback.

I pushed a change to the main branch that should address this issue.

I tested it by opening two terminals and running the following

1. python -m demo.echoserver
2. python -m demo.echoclient

**Comment by Tom11w** [comment]
Hello,
The change to the main branch seems to fix the SSL issue for me, but the change isn't reflected in PyPI.
Note: This could be my fault, I am just a new programmer enjoying trying to build a multiplayer game.

**Comment by nsetzer** [comment]
I deployed a new version, sorry about that
